### ISSUE TITLE
electron-rebuild failed

### ISSUE THREAD

**Issue by junbujianwpl** [JCMais/node-libcurl#206]
I want to use this in my electron project, but fail to install. 
* OS: win10 x64 
* node: 13.5.0 
* electron: 5.0.10 
* yarn:  1.19.2 
* npm: 6.13.4 
* problem: Install node-libcurl succeed but electron-rebuild failed
* produce: run the script for electron on windows as follow

~(As for macOs@10.15 Catalina, I cannot create /usr/include dir even with root privilege. I didn't try to disable the SIP, which seems a little hack for me. We cannot just open the SDK.package file to solve the compilation errors. Maybe update the gyp configure is a better way for the compile issue on Mac.)~

**This works on Mac@10.15.0**

```npm_config_curl_include_dirs=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ npm_config_build_from_source=true npm_config_runtime=electron npm_config_target=5.0.10 npm_config_disturl=https://atom.io/download/atom-shell yarn add node-libcurl```

The install style on windows may be improper. But I didn't make it work with guidance. Or maybe rebuild from source for electron was tricky as the compiler complained header file not found. Maybe `apt install libcurl-devel` will do the job for the compiler on Linux. But it is not a straightforward way, especially on windows. Maybe I should specify the `npm_config_curl_include_dirs` and `npm_config_curl_libraries`.

> a@pc MINGW64 /d/workspace/js/my_project (node_lib_curl)
$ npm_config_runtime=electron npm_config_target=5.0.10 npm_config_disturl=https://atom.io/download/atom-shell yarn add node-libcurl
yarn add v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.1: The platform "win32" is incompatible with this module.
info "fsevents@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ node-libcurl@2.0.3
info All dependencies
├─ node-libcurl@2.0.3
└─ node-pre-gyp@0.13.0
$ ./node_modules/.bin/electron-rebuild -r 5.0.10 -w diskusage
× Rebuild Failed

> An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@13.5.0 | win32 | ia32
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [
gyp info spawn args   'D:\\workspace\\js\\my_project\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\workspace\\js\\my_project\\node_modules\\node-libcurl\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\workspace\\js\\my_project\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\a\\.electron-gyp\\.node-gyp\\5.0.10\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\a\\.electron-gyp\\.node-gyp\\5.0.10',
gyp info spawn args   '-Dnode_gyp_dir=D:\\workspace\\js\\my_project\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\a\\.electron-gyp\\.node-gyp\\5.0.10\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\workspace\\js\\my_project\\node_modules\\node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\workspace\\js\\my_project\\node_modules\\node-libcurl\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn msbuild
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
gyp info spawn args ]
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
  node_libcurl.cc
  Easy.cc
  Share.cc
  Multi.cc
  Curl.cc
  CurlHttpPost.cc
  CurlVersionInfo.cc
  win_delay_load_hook.cc
d:\workspace\js\my_project\node_modules\node-libcurl\src\share.h(11): fatal error C1083: �޷��򿪰����ļ�: ��curl/curl.h��: No such file or directory
(����Դ�ļ� ..\src\Share.cc) [D:\workspace\js\my_project\node_modules\node-libcurl\build\node_libcurl.vcxproj]

**Comment by JCMais** [comment]
Could you share a sample code you are trying to run so I can run it myself and try to find the problem?

**Comment by JCMais** [comment]
This should be fixed on the pre-release version, could you try?

```
yarn add node-libcurl@next
```

**Comment by JCMais** [comment]
I'm closing this as [v2.1.0](https://github.com/JCMais/node-libcurl/releases/tag/v2.1.0) (see the release page for full changelog) has been finally released. 🎉
