### ISSUE TITLE
GLIBC 2.14 issue

### ISSUE THREAD

**Issue by vncodehorror** [JCMais/node-libcurl#44]
Hi

I installed but not working. It throws error saying "/lib64/libc.so.6: version `GLIBC_2.14' not found"

OS: Centos 6.7 Final
glibc 2.12
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

Is there any way to make this work on centos 6.7. Because no way to upgrade glibc to 2.14, as we hosted on dedicated server and the data center not support to upgrade to centos 7

**Comment by vncodehorror** [comment]
UPDATED:

I tried with --build-from-source, here is error

make: Entering directory `/root/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
  CXX(target) Release/obj.target/node_libcurl/src/Easy.o
../src/Easy.cc: In static member function ‘static size_t NodeLibcurl::Easy::ReadFunction(char*, size_t, size_t, void*)’:
../src/Easy.cc:306:22: warning: unused variable ‘len’ [-Wunused-variable]
         unsigned int len = (unsigned int) ( size * nmemb );
                      ^
../src/Easy.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NodeLibcurl::Easy::SetOpt(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Easy.cc:610:34: error: ‘CURLE_UNKNOWN_OPTION’ was not declared in this scope
         CURLcode setOptRetCode = CURLE_UNKNOWN_OPTION;
                                  ^
make: *** [Release/obj.target/node_libcurl/src/Easy.o] Error 1
make: Leaving directory `/root/node_modules/node-libcurl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/node_modules/node-libcurl/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-573.12.1.el6.x86_64
gyp ERR! command "/usr/bin/node" "/root/node_modules/node-libcurl/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/root/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /root/node_modules/node-libcurl
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

Any advice?

**Comment by JCMais** [comment]
What is the libcurl version being used?

**Comment by vncodehorror** [comment]
I think libcurl 7.6. What version you advise

**Comment by JCMais** [comment]
That is really really old (almost 15 years old). The addon has support for versions above 7.30. But if you can, try installing the latest one, 7.46.

**Comment by vncodehorror** [comment]
Thanks @JCMais works
For future reference

Check latest release here http://www.city-fan.org/ftp/contrib/yum-repo/rhel6/x86_64/repoview/city-fan.org-release.html

```
        $rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/rhel6/x86_64/city-fan.org-release-1-13.rhel6.noarch.rpm
        $yum update libcurl
        $curl-config --version
          libcurl 7.46.0
```
