### ISSUE TITLE
Can't build using node 16.0.0

### ISSUE THREAD

**Issue by lasertiger** [JCMais/node-libcurl#285]
I've tried on a mac and Ubuntu 18.04 and Ubuntu 16.04.

Same on both:
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8.h:30:0,
npm ERR!                  from /home/ubuntu/.cache/node-gyp/16.0.0/include/node/node.h:63,
npm ERR!                  from ../node_modules/nan/nan.h:56,
npm ERR!                  from ../src/Curl.h:13,
npm ERR!                  from ../src/node_libcurl.cc:7:
npm ERR! /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
npm ERR! /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:33: error: ‘remove_cv_t’ is not a member of ‘std’
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                  ^
npm ERR! /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:33: error: ‘remove_cv_t’ is not a member of ‘std’
npm ERR! /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:50: error: template argument 2 is invalid
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                   ^
npm ERR! /home/ubuntu/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:61: error: ‘::Perform’ has not been declared
npm ERR!              !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                                              ^
npm ERR! ../src/node_libcurl.cc: In function ‘void NodeLibcurl::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
npm ERR! ../src/node_libcurl.cc:61:36: error: cannot convert ‘void (*)(void*)’ to ‘node::Environment*’ for argument ‘1’ to ‘void node::AtExit(node::Environment*, void (*)(void*), void*)’
npm ERR!    node::AtExit(AtExitCallback, NULL);
npm ERR!                                     ^

**Comment by JCMais** [comment]
I have not updated the code to run with Node.js v16, I will do so in the following week

**Comment by JCMais** [comment]
v2.3.3 has been released.
